# Nixpacks configuration for Railway
[phases.setup]
  nixPkgs = ["nodejs_18", "python3", "python3Packages.pip"]

[phases.install]
  cmds = [
    "npm ci",
    "pip install -r requirements.txt"
  ]

[phases.build]
  cmds = ["echo 'Build complete'"]

[start]
  cmd = "npm start"
